[package]
name = "postg-arrow"
version = "0.1.6"
edition = "2021"
license = "MIT"
description = "Arrow integration for postg-rs via native Postgres binary protocols"
repository = "https://github.com/oonid/postg-rs"

[dependencies]
sqlx = { version = "0.8.6", default-features = false, features = ["postgres", "runtime-tokio-rustls"] }
arrow = { version = "59.2.0", features = ["csv"] }
futures = "0.3"
bytes = "1"
postgres-types = { version = "0.2", features = ["with-uuid-1", "with-serde_json-1", "with-chrono-0_4"] }
postgres-protocol = "0.6"
tokio = { version = "1", features = ["macros", "rt"] }
anyhow = "1"
async-stream = "0.3.6"
parquet = { version = "59.2.0", optional = true }

[features]
parquet = ["dep:parquet"]
